---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vetcare-admin-app
  namespace: vetcare-admin-dev
spec:
  encryptedData:
    AUTH_SECRET: AgA6taG3nKsW4bp7NHwbtkaSz41UP+KhB7cCvX0drLhks9svkIvnXjTTXLpZ+LZvVW2NaGdn3h6fLhz1NKvD69cp5fjh+iGYDpAbtNn2pH/IN4S+BZRfYm8lWsB8dWAjDL4/sn4tPJ0C+2iCKS48DAUL5jYNmlZaKhIRhpwqX06EVra+6VXCtC1gdTJvP3rgrIZMxVwfX2yDuSSMvui3iCaPg09mzGAWqUgkkWKNwY5edrdC680diF40s1w0gCOj0qO53sqQ/Uv6zy5xgv0YlFTRqyNmfhZaU/cPSWnCh/DuF1DQ2VlhihtPyzzs6u5mIq8jJe3sc0EYXyqNU3WPTVa8qim8fiyKarhU3TFPtQAW/wegCNFcwVoXJcnDd2KQfxnfNyZY4YccWOE1nBLxC6XWeCXCZUkaVnv9NU/SX2aQ8APMxCRcxaIzBM6+iM2oTaHYmuV5yaF2OhvSGZMexIooglFsWJcRezIa4k0GyVbu3cUbQhfxLe3mSa0pxGcWEjmKiRLXwzSTi/QcbF5njVIp96yRmACVzF+H+wfD9VmoopMz18BJblsp74M5Aj7WiyuPhz7DQq5+spGAKD9aloWxNgOEXrERKjnjpdjUnHr/FvlIJvmgQbgbswGCheAJFL445uDdmVgc9gfALmbHZ5+Eg4VJG51m/nBoWGK5K1IvZ3TkDxcNdCYZaaY6YChr4kfFppDDAKbjLBOWXwAM7a/jkKp9ut6hWoAPAcDLX2NbExz77FVNxTiMDXgtjg==
  template:
    metadata:
      name: vetcare-admin-app
      namespace: vetcare-admin-dev
