---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vetcare-admin-registry
  namespace: vetcare-admin-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBtje1nAH6k9UWyyTBdToAJ+ZxDNbtav9eoA1Z1v8Fcuo2U6zejaILO9uCjVuKU38C4+p2n7Qe90MwoohVW27K+WK8BCNDcgvtjwyZ/4sDkZOh9kV7SM5SRQXL/7SxFq+vCWtAcwSp2uqPVWTXM6kV3wwZhuWyNNs5pqc0RdwyDMRjoZV6CoZp8rWAgedlzsAYulJwQXvXtT5eZxioP0QH7gU3/0eD2yRnClQ1KtL0w5zumjbg3qVv4PXVatW5TIfUesHG/EGOM0wxkENtS4Wn2uinAe1g+Vt9Ln+avxAdlea/MBETQnDZMfEv44jlnVlRfnupKDYkj1gS7xrb65AvBa8PlMLOjoFBalqpsGIa26BaIgXV5mogZhkVxnZsLB/o6M3mQqlEHjKurPEOwV+qyY0Yp/Y/fNeVYD4WGezU4yc8gwofSiVg8dMi5SnY9ZMldXJiO5RP86EtRwdJ3KKuspA+OQNrCdYN2yZzT6asZKugNISQuC/DOVOgU6fWZ0IQaOelhIm+7vL2GsG28M0Lnc2bFMgyyDIYV8MtjraZ6tOV1iD61IoWq8kMHEKb4kydmLwuteT6BVCY35W1EhDE3JnqYaUIoYyWvRXtdGmPuQG1jzo4GUbYn/Z92maL6/gAU85mm8EZwxAcglpkPUL2KLG5xbOvxb0tCyz0vInVjjzj14ZG0HfugzaHvWvRbMoHnxIkOwppCLFIlsfbmwTsOO5pgJiw5E3N6nbIyEpbkv7ADwbXQe1aw/e6ZnaVeaBfzejZ9dwfgOibU9Sqop/uuLa51Fc43xC/8ltkInfsYnfeVMrC6kIt5+UAnBWlrhaAHrkWDgYj9sMpARynUtoBj3reDgVDMt1Q8KJmwTGUKhVk8FYhnzT4bVNCg8y3y+PoswcCkqUgMNoMM46jtmRQULaIvpVriwvRpKFhoLDQjEoQSFrjQcW3nx1vpSsC+SbaCO6IQcMfiXR2mRZ/bqtI=
  template:
    metadata:
      name: vetcare-admin-registry
      namespace: vetcare-admin-dev
    type: kubernetes.io/dockerconfigjson
