apiVersion: v1
kind: Service
metadata:
  name: {{ include "push-notify.appFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: push-notify
    app.kubernetes.io/name: {{ include "push-notify.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: push-notify
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.containerPort }}
