apiVersion: v1
kind: Service
metadata:
  name: {{ include "server-control.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "server-control.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "server-control.selectorLabels" . | nindent 4 }}
