---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vetcare-backend-registry
  namespace: vetcare-backend-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCKe+IO6G2ND6pKAJ75pU7OPDw3ojc7TSmaQLBD/p6HvJX3ORBosPVt4RDGeZ/NVvIXD0RSoG0AHZFOHMfju9svIEZ+CdpWa+Thx3pXyEkZkEI1ZfqM35fJjBkreMEnDOE2XgwLJbTnv49Oit634PYC0JWY2xCwIoQhw22ZZBBCsTU2rgvhz72dBUqve/OYWvv+ma4tqBBrsrvCKHFkHwj4OouhXXM56G+ilUYIdIMRE94jqaWQo+5WJ6/nHMtgOUmKhA/VbcjoTDjh6dhxTpivT8gTXSLmmdl35AN03YI+zK7MrIBPiwPrHgF4N0jeJgMbNkMYQz7NJmLTLyqtordDi5yrq94vRV7nlbQmQhSjtdMlwo+sH179kKlAwgnpA5toh8n7KSc9PAEvWrsUVKar/Za56hX3pyoI28TvpFSPpWuhTqrjIgJ1MyuCNfHYjq8Ht4Z+SZm4fLyD4jVAZtLiozsTknQcMJEKx9gbx14tLL+Iv3VqTNZEx2tTY6k9fhDMRxjIKrFAmghmfPAnCSFwKGjryDhm9c3ZA7mwMmwSu2IApYNzdxkxXK8l/vFU4JG+mVLyWizseEifUcaUftMV9mQvGudvr1S8qskY9Zd59Lb9/G3TGEvw3M9DLyjZ0DBSqI9uh/tpf5yAEKRUWKPjj6KjiZ5xP5xldU9boYgTtlS0ZFd64mvgTRI01rAQj6MrOgfHNfGWx9Sc9+JL5Db2dXT6ufLDKPqpAD0BzsXD3oFNNgqI+PHJMk1WH7/lOCCfrQUiMFHQL5mzvE0AnkojSD/8R8uenSkKZvUEtV0TSE5QPxKaYVNBjX6dfbJRzrYulStr7QVme+nuRgdDfBw7nCEMxIPqZ15IrGsPewOpVIB+FN8bVPjZZ1Tgtp7ZNhRPtwgkmsIGqk70Y6FHiAAx5tBaHTXTeOhVJr3VS97BbtRpSsNEipNz4bud5oY/I1fr5aSOT2MSR1nbfLEEI5A=
  template:
    metadata:
      name: vetcare-backend-registry
      namespace: vetcare-backend-dev
    type: kubernetes.io/dockerconfigjson
