---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: storage-minio-credentials
  namespace: storage-minio-dev
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAjjN956S1AdyONhalNyllJI3YpmPQ70KcpoVecmxG+zqkUJeiwHiWv5w7hgSaPDx7sHcR47exeGPDaEmmxiDOzWL7/CzbDdh9zvfWWxA5WFZjTRitvm5AmBwf42h0OJWHYgfQEwLi0+dSVXwMHNSbckYWA9OuLSsxDoaZWmNMo5Z1Z8+BAkKf0tBv6nfd6EjFqzwTbHQr8udNpCpK9dK7DxXeR61yQth6hrVoYTG+HnWTcDzqYgyRXgjOiooAu5L42EI7OlzRyKRlwR0y/qTsXmq8cfgUS3f4rS3PMwVjReWRT0CU6Dm+mGBif0jvPxjbgwnH0Uk+br9xncTUfwFRmUKsOBB1olLXAc6jTkidSzA0BrcnP7wUFz7a7YYm9pPYiDavwWWLk04XOQ1khf5pHRZU947+TizfYGNtpd/MfXJc2o6TXs+71QoDhTq9ktlHnZE1sKDLQLU49ULmgJctGe6/0Ovh2c0fWj9l8FWpzuWTvxtDjQ+y5qApb5jeqekQn6/iYOe25uqenh42vZXmemMjAPhFivNInnuDZhh2Q1Rkj3hpyYAFB0I6qmVnuKpfnXQY7GKw8nUjHTIffsT9h7wdNpF647Y6IcTkIrWL14l7mbKTFjWKL1QR9fPZdEoAF0+p7c9m7h+M47aQ3QG6O994j55FcjvqWeIuFSKhe/kTC2++xMTnM7HONGfnbu3V83DdZyqaP0C+ml2/TEL6RafLQywe382oNW7lqkb3YjoNptXBb0wXp
    MINIO_ROOT_USER: AgBP8ChrdDcJLVlgPYELVXMYFDz1g080L72kZ5qX4OVHDsQfR41gdo9YGadrTdqzqjI9x8rm9EPihmjr50355lIS5hsQFeIcsZB8ZIKgeV0rA34ercMicSKXxRzfQuCKoDDZzvh1+LF1crJmYvXFDDarG409hgSCusvVvpUlELp9HUBCnilo5phZ8CmFda2WKQIc7UODO9DSGM3OgHxe4TX3CkIK+/DOL7+ZyHHm3r9Z+O3pjiqXtLwr2Xcdr3Oxx51zVY50JqYoj2TnGCj/74WRiwfse3V3Cpa3JfuRoop33xc1UzD8qyjZwKuU6EDXPbTEj5cj2v0TbLfTKxEQmxvdmyhwHYy+jfVG9/NpIVnOM+zmWNJ4z3ByMxqZY7Qi6yovlYqOQSrR4efNSiecJebmDr+8VdV+NGeAnyG4+TxxJxXIGo/nqwd0newfsH6OElSjxzshpUpxPVjZ94na4ajKLM1Ae/d23WbRLBhIqPOI4DTQXun4RFPK4sfgmJKsGR2aEANGZEHtZzhaWA0aQCtStb9PRQujG7oQ7hnEO16Rhjri3p+6Kwc0pDk3jwm9a9naTQE2WFwwJbGKLh8zqs9zmYEEgKzjd/2cbRsy0tPpcj2hmzecPw4egeiKrVEd3mOjLXsNFt4vHonH+qHsXpOP7CVzkYSIzEh7Zl+1ozl9tY9jwZMLPTkxDTg/LP7N6aMibXJpcjRmvq3U
  template:
    metadata:
      name: storage-minio-credentials
      namespace: storage-minio-dev
