apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giaan-clinic-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/hnq-tech/hnq-infra.git
    targetRevision: main
    path: infra/helm/clients/obgyn-clinic-service
    helm:
      releaseName: giaan-clinic
      valueFiles:
        - values.yaml
        - giaan-clinic/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: giaan-clinic-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
