apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName | default "obgyn-clinic-service" }}
    app.kubernetes.io/environment: {{ .Values.global.env | quote }}
