apiVersion: v1
kind: Secret
metadata:
  name: push-notify-v2-config
  namespace: push-notify-v2-dev
type: Opaque
stringData:
  DB_HOST: "mariadb.storage-mariadb-dev"
  DB_PORT: "3306"
  DB_NAME: "push_notify"
  DB_USER: "root"
  DB_PASS: "replace-me"
  INTERNAL_API_KEY: "replace-me"
