apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-opensearch-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@gitlab.com:hnq-tech/hnq-infra.git
    targetRevision: develop
    path: infra/helm/platform/storage/opensearch
    helm:
      releaseName: opensearch
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: storage-opensearch-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
