global:
  namespace: storage-mariadb-prod
  env: prod

persistence:
  hostPath: /home/hnq/hnq_data/prod/platform/storage/mariadb

resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

nodeSelector:
  kubernetes.io/hostname: hnq-server-vietnix-01-hjnu
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
