global:
  namespace: storage-opensearch-dev
  env: dev

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-dns01-dev
  host: storage-opensearch-dev.l2cteam.work
  tls:
    enabled: true
    secretName: storage-opensearch-dev-tls

persistence:
  hostPath: /data/k3s/dev/platform/storage/opensearch
  size: 20Gi

resources:
  limits:
    cpu: 1500m

nodeSelector:
  kubernetes.io/hostname: server02
