apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-k3s-dual-access-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/hnq-tech/hnq-infra.git
    targetRevision: main
    path: infra/argocd/manifests/platform/traefik-k3s-dual-access
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
