apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "opensearch.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch.fullname" . }}-headless
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "opensearch.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics

