{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "postgres: password is required when existingSecret is not set" .Values.auth.password | quote }}
{{- end }}
