debug: true
server:
  address: ":10080"
context:
  timeout: 2
database:
  host: "mariadb.storage-mariadb-dev"
  port: "3306"
  name: "lotus_clinic"
gorush:
  address: "gorush"
  port: "10088"
logging:
  config:
    level: debug
    disableCaller: false
    encoding: "json"
    outputPaths:
      - "stdout"
    errorOutputPaths:
      - "stderr"
    encoderConfig:
      timeKey: "ts"
      levelKey: "level"
      nameKey: "logger"
      callerKey: "caller"
      functionKey: ""
      messageKey: "msg"
      stacktraceKey: "stacktrace"
      lineEnding: "\n"
      levelEncoder: "capital"
      timeEncoder: "ISO8601"
      durationEncoder: "s"
      callerEncoder: "short"
  logPath: "/var/log/giaan/l2c_notify_service.log"
  rotate:
    maxSize: 1
    maxBackups: 2
    maxAge: 30
