app_env: local
http_port: "10080"
internal_api_key: internal-secret
database:
  host: "mariadb.storage-mariadb-dev"
  port: "3306"
  name: "db_push_notify_v2_dev"
  charset: "utf8mb4"
  parseTime: true
  loc: "UTC"
logging:
  config:
    level: debug
    disableCaller: false
    encoding: "json"
    outputPaths:
      - "stdout"
    errorOutputPaths:
      - "stderr"
    encoderConfig:
      timeKey: "ts"
      levelKey: "level"
      nameKey: "logger"
      callerKey: "caller"
      functionKey: ""
      messageKey: "msg"
      stacktraceKey: "stacktrace"
      lineEnding: "\n"
      levelEncoder: "capital"
      timeEncoder: "ISO8601"
      durationEncoder: "s"
      callerEncoder: "short"
  logPath: "./logs/pushservice.local.log"
  rotate:
    maxSize: 1
    maxBackups: 2
    maxAge: 30
push:
  firebase:
    service_account_path: ./configs/service-account.json
run_migrations: false
run_seed: false
worker_poll_interval: 3s
scheduler_interval: 5s
fanout_batch_size: 100
max_delivery_retry: 3
push_multicast_enabled: true
push_multicast_batch_size: 500 # Firebase allows up to 500 tokens per multicast message
